### PR TITLE
move to LiteXModule

### PR DESCRIPTION
**Pull request by maass-hamburg**
@enjoy-digital 
move to LiteXModule

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @maass-hamburg!

**Comment by enjoy-digital** [comment]
Would you mind fixing the conflicts? we could then merge.

**Comment by maass-hamburg** [comment]
> Would you mind fixing the conflicts? we could then merge.

@enjoy-digital sure

**Comment by enjoy-digital** [comment]
Thanks @maass-hamburg, this is merged.

**Pull request merged**
