### PR TITLE
Litespi - using the ODDR/IDDR, simplifying models 

### PR DESCRIPTION
**Pull request by pawelsag**
With this PR the litespi:
 - has simplified PHY core. CMD and USER states have been reimplemented as USER state in MMAP core.
 - implements the PHY using the ODDR/IDDR cores.
 
 We updated the model.py and tests so they are compatible with new implementation.
Litex PR related to this change can be found under this : https://github.com/enjoy-digital/litex/pull/1024

### CODE REVIEW

**Comment by zyp** [comment]
The clkgen changes doesn't account for when the clock is output through the `STARTUPE2` or `USRMCLK` primitives. I also seem to recall that the bottom bank on the ECP5 doesn't have DDR registers at all.

**Comment by pawelsag** [comment]
@zyp we decided to leave the legacy mode which can be configured with the option.
With this change, we can use the DDR version on devices that supports it and
if this is not possible we can switch to the legacy implementation.
What do you think about such solution?

**Comment by piotr-binkowski** [comment]
I've just added 2 commits that modify MMAP and DDR PHY FSMs a bit to reduce read times by 3 cycles which improves sequential read throughput

**Comment by enjoy-digital** [comment]
Thanks @pawelsag, @piotr-binkowski, this provides a better decoupling between the PHY and the Core. I just tested it on Arty (with the DDR PHY) and it's working correctly. I'm merging and will do more tests the other boards from LiteX-Boards already having SPI Flash support to make sure the clk primitives are used correctly when required.

**Comment by enjoy-digital** [comment]
The code has been rearranged a little bit with https://github.com/litex-hub/litespi/commit/b571dd3220392f6e68ac74e0717d35a9fc0e91c0.

**Pull request merged**
