### PR TITLE
mmap: Add write functionality

### LINKED ISSUE #25: Support the SPI RAM found on HAD badge
The [HackADay badge](https://hackaday.com/2019/11/04/gigantic-fpga-in-a-game-boy-form-factor-2019-supercon-badge-is-a-hardware-siren-song/) has
> two Lyontek LY68L6400 64 Mbit SPI SRAM chips

These SPI SRAM chips, *kinda* look like SPI NOR chips.

It would be good to have these devices supported as memory mappable for both read and write.

Clock rate:
- 33MHz(max) for normal read
- 100MHz(max) for fast read
- Mode: SPI/QPI

Datasheet -> https://www.electrodragon.com/w/images/0/04/LY68L6400_0.3.pdf

### PR DESCRIPTION
**Pull request by m-byte**
With this change, it is possible to memory map e.g. PSRAM. When setting with_write to "csr", it can also be used to support faster flash writing via etherbone. For flash, only False and "csr" should be used, as the some other logic or application needs to make sure that the flash is erased ahead of time. True is only meant for use with RAM chips.

There are two bugs that this also addresses:
1. ~~Addresses are now masked to flash size or addr_width if no size is set. I'm not 100% happy with this solution, as it might cause issues with non power of 2 flashes (do those exist). However, without this, I would get flash writes to the wishbone address rather than offsets inside the flash. So I'm open to better alternatives. Optimum would be subtracting the base bus address, but I haven't found any clean way of accessing it.~~ I found a way to wire the origin through, so now this can be fixed by wiring through the corresponding addresses (described in the commit message and I will create a PR for LiteX, once this is merged)
2. In quad mode the core was driving all pins for the duration of the dummy bits. Now, the pins are released at the start of the dummy period to not interfere with the pins being driven by the external chip.

Let me know if they should be part of separate ~~commits/~~ PRs.

~~Currently, tests are still to be added.~~

This should fix #25

### CODE REVIEW

**Comment by m-byte** [comment]
@enjoy-digital should the CSR functionality also be tested? If so, is there any recommended approach?

**Comment by m-byte** [comment]
@enjoy-digital do you think you would find to review this soon?

**Comment by enjoy-digital** [comment]
@m-byte: Thanks for the PR and sorry for the delay...! I'll review it before the end of the week.

**Review by enjoy-digital — APPROVED** [review]
Thanks @m-byte, this make sense and the code look fine, let's merge. Thanks also for the test-bench, really appreciated and help a lot for future maintenance!

**Comment by m-byte** [comment]
Thank you!

**Pull request merged**
