### PR TITLE
tests: fixup and update

### PR DESCRIPTION
**Pull request by maass-hamburg**
@enjoy-digital 
-  simplify tests
- fix test

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks at lot @maass-hamburg! Would you mind creating a different PR for the CI Improvement/update? I generally try to keep this similar between the different repositories, so would handle this a bit later for all repos.

**Comment by maass-hamburg** [comment]
@enjoy-digital sure, the ci improvement is now there: https://github.com/litex-hub/litespi/pull/76 and has been remove from this PR.

**Comment by enjoy-digital** [comment]
Thanks!

**Comment by enjoy-digital** [comment]
Thanks @maass-hamburg, this is merged.

**Pull request merged**
